# File: tests/Makefile
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = ../hdl/xor_gate.v
TOPLEVEL = xor_gate
MODULE = test_xor

include $(shell cocotb-config --makefiles)/Makefile.sim

wave:
	gtkwave waveforms.vcd &
